name: CI

on:
  push:
    branches: [main]

env:
  GRAPHQL_API_URL: https://api.tsinghua.app
  GRAPHQL_ADMIN_SECRET: ${{ secrets.GRAPHQL_ADMIN_SECRET }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Typecheck
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - name: Build
        run: yarn build

  deploy:
    needs: [check]
    runs-on: ubuntu-latest
    env:
      USERNAME: $GITHUB_ACTOR
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CONTAINER_NAME: tsinghua.app-web
    steps:
      - uses: actions/checkout@v2
      - name: Login into registry
        run: echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $USERNAME --password-stdin
      - name: Build Docker image
        run: docker build --build-arg GRAPHQL_API_URL=$GRAPHQL_API_URL --build-arg GRAPHQL_ADMIN_SECRET=$GRAPHQL_ADMIN_SECRET -t docker.pkg.github.com/$GITHUB_REPOSITORY/$CONTAINER_NAME:latest .
      - name: Push to registry
        run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$CONTAINER_NAME:latest
